### ISSUE TITLE
support testing console applications with pytest-embedded (RDT-237)

### ISSUE THREAD

**Issue by igrr** [espressif/pytest-embedded#106]
Although somewhat outside of the _embedded_ scope of pytest-embedded, it would be convenient if we could test console applications using pytest-embedded as well.

ESP-IDF now supports building for the `linux` target, and the result of such a build is a console application. Similar to the applications running on the chip target, we could use `expect` and other features of pytest-embedded to check that such an application runs correctly.

This is especially convenient if the given test application can be built in IDF both for `linux` and for a chip target. Then we could write a test case which works for both builds, the only difference being the service provided by pytest-embedded (`idf` or `console`). This is similar to how we can already use the same test for QEMU and for a chip target.

**Comment by hfudev** [comment]
`pexpect.spawn` is not available on Windows, we should use `DuplicateStdoutPopen` directly for the executable.

**Comment by hfudev** [comment]
closed by #175
