### ISSUE TITLE
command line arguments and addopts (RDT-253)

### ISSUE THREAD

**Issue by KaDw** [espressif/pytest-embedded#113]
It is great that you managed to add `--baud` option to the tool. 

I'm using Windows 10 and a FT232 serial adapter.
I noticed minor issue while passing arguments to the service:

- `addopts = --embedded-services serial -s --port COM3 --baud 921600` tests executed with `pytest` command works fine
- `addopts = --embedded-services serial -s --port COM3` tests executed with `pytest --baud 921600` command works fine
- `addopts = --embedded-services serial -s --baud 921600` tests executed with `pytest --port COM3` command fails with error `OSError: [WinError 6] The handle is invalid`

My goal is to specify the port from the command line.

**Comment by hfudev** [comment]
@KaDw

》 addopts = --embedded-services serial -s --baud 921600 tests executed with pytest --port COM3 command fails with error OSError: [WinError 6] The handle is invalid

Could you give this command a try? `pytest --port COM3 .`?

**Comment by KaDw** [comment]
Adding the dot at the end of command works! What is the purpose of it if I may ask?

**Comment by hfudev** [comment]
TBH I have no idea why it happens... didn't look into the pytest project code that deeply.

According to my personal experience, sometimes the positional argument `file_or_dir` for pytest is not stable with some special argument. Declaring it explicitly would solve this problem.
