### ISSUE TITLE
Add CLI switch to skip flashing (RDT-59)

### ISSUE THREAD

**Issue by morganrallen** [espressif/pytest-embedded#14]
Hi checking out the project as a possible future solution for CI testing esp32 application code.
One of the first thing I noticed is the device is flashed every time, regardless of actual changes to the binary.
This dramatically slows down test writing, especially when many small tweaks to the pytest side of the test code are required.
Would be nice to include a switch to skip flashing.

**Comment by hfudev** [comment]
@morganrallen Thank you for your idea!
