### ISSUE TITLE
[idf] replace threads in MultiDevCaseTester (RDT-317)

### ISSUE THREAD

**Issue by alekseiapa** [espressif/pytest-embedded#162]
Currently we use threads for the serial output redirection purposes. Python Global Interpreter Lock might cause the block of the threads. In order to avoid block we should reduce their amount

**Comment by hfudev** [comment]
besides. the "fake test case" issue with ESP-IDF unity multi device test cases still exists. The single board issue has been fixed in #166

**Comment by hfudev** [comment]
@horw PTAL. Besides, some modifications are done in https://github.com/espressif/esp-idf/blob/master/tools/ci/idf_unity_tester.py#L180. Please pull those changes in as well.

Our future plan is to replace the code in `esp-idf` with this one.
