### ISSUE TITLE
Use pyproject.toml and poetry instead (RDT-355)

### ISSUE THREAD

**Issue by hfudev** [espressif/pytest-embedded#180]
- [x] use ruff as the linter. enable more rules (https://github.com/charliermarsh/ruff)
- [x] one pyproject.toml for all configurations (https://python-poetry.org/docs/pyproject/#packages)
- [ ] Use poetry instead. rewrite setup.py
- [ ] Enable docstring checks as well.

**Comment by kumekay** [comment]
Flit may be a better option https://github.com/pypa/flit ?

**Comment by hfudev** [comment]
This should be partially done by https://github.com/espressif/pytest-embedded/pull/213

Create #218 for a follow-up task regarding the docstring check.
