### ISSUE TITLE
pytest-embedded-serial leaves files open after test (RDT-363)

### ISSUE THREAD

**Issue by JammuKekkonen** [espressif/pytest-embedded#185]
Running tests using pytest-embedded-serial, eventually either OS or python runs out of file handles as the framework seems to leave open file handles after test execution ends. Attached is a example case with three duts, to me running this fails systematically at test 167 and beyond with
> ValueError: filedescriptor out of range in select()

Note: might need to increase OS file handle limit to hit Python's limit above, other option is that tests start to fail with
> OSError: [Errno 24] Too many open files

Environment:
Debian Linux
Python 3.9.2
pytest-embedded 1.2.1
pytest-embedded-serial 1.2.1

[test_open_files.zip](https://github.com/espressif/pytest-embedded/files/10508657/test_open_files.zip)

**Comment by hfudev** [comment]
@JammuKekkonen Thanks for reporting this issue. I can reproduce locally. I'll take a look.

**Comment by hfudev** [comment]
@JammuKekkonen the bugfix version 1.2.2 has been published. Please have a try.

**Comment by JammuKekkonen** [comment]
@hfudev I can confirm that bug is fixed in 1.2.2.
Thanks for the quick reply and fix!
