### ISSUE TITLE
Fix DeprecationWarning: 'telnetlib' is deprecated and slated for removal in Python 3.13 (RDT-365)

### ISSUE THREAD

**Issue by hfudev** [espressif/pytest-embedded#189]
related PEP https://peps.python.org/pep-0594/#telnetlib

**Comment by AlaBouali** [comment]
hello guys, please try my alternative to telnetlib:

https://github.com/AlaBouali/xtelnet

> This is an easy to use telnet module to interact with a remote system smoothly over this protocol! It is a very minimalistic alterative to "telnetlib". xtelnet is a powerful and user-friendly Python library designed for managing Telnet sessions with ease and efficiency. With its intuitive interface and robust functionality, xtelnet simplifies the process of interacting with Telnet servers, offering a range of features for seamless communication. xtelnet offers a comprehensive solution for Telnet communication, providing developers with the tools they need to effectively manage Telnet sessions and interact with remote systems. Whether you're a seasoned developer or new to Telnet protocols, xtelnet empowers you to achieve your goals efficiently and reliably.

Why should I use xtelnet?
Easy to use and stable
Simple Authentication mechanism
Compatible with almost all servers when it comes to authentication and executing the commands
Available Command line tool
Thread-safe: if the session is shared among threads to execute commands, the commands will be executed one by one
Supports running multiple sessions concurrently
Can connect simultaneously and run in parallel the same command on: single or some or all connected hosts
Allow reconnect after closing the connection
Allow escape ANSI characters
Grab banners
Available "ping" function to use if you want to keep the connection open
Supports SOCKS 4 / 5 proxies
Supports SSL
Supports sending JSON data
