### ISSUE TITLE
one process - one dut (RDT-520)

### ISSUE THREAD

**Issue by horw** [espressif/pytest-embedded#224]
**Introdution**
I suggest key issue why pytest-embedded can't use multiprocessing rn lies in the fact that dut object init in the main process, and after init we try to pass this object to another process, there are not clear usage of object replica.

**Related**
#162 

**Thoughts**
  Pytest-embedded is a test framework, and maybe its possible separate responsibility between **test** and **controlling device** tasks.
  Pytest-embedded can implement main process like a publisher, which only responsible for tasks and results, its don't worry about dut itself. Dut-control processes are subscribers, when one of them receive commands, it start work around how to run this test case, this means publisher delegate this responsibility. Every dut init in this dut-control processes inside, through main process collect class parameters and send them to dut-control processes. Maybe here we also can delegate responsibility of collection parameters to dut-control, and just send needed console args parameters.

**Schema**
![image](https://github.com/espressif/pytest-embedded/assets/47724762/2f1c0fd6-87d1-4873-805a-671f7178a92a)

**Summary**
In this way pytest-embedded objects responsibility will be more clear. And it will help pytest-embedded framework achieve better results in task parallelism.

**Comment by hfudev** [comment]
related #162

**Comment by horw** [comment]
It not possible to implement it, because need refactor all methods and api. Also have some issue with support: on one side need update api, and on another side need update client logic(dut), double work.
