### ISSUE TITLE
Support `expect` With `not_matching` (RDT-636)

### ISSUE THREAD

**Issue by hfudev** [espressif/pytest-embedded#257]
For example

```python
dut.expect('foo', not_matching='bar')
```

Will fail

```
bar foo
```

But pass

```
foo bar
```

check the `pexpect_proc.buffer` after a success match would be a quick solution.

**Comment by gytxxsy** [comment]
If possible, would it be more better to allow not_matching to be a list? Such as:
```python

dut.expect('foo', not_matching=[‘A’, 'B', ‘C’]) # The order of A B C is not strictly required
```

**Comment by hfudev** [comment]
> If possible, would it be more better to allow not_matching to be a list? Such as:
> 
> ```python
> dut.expect('foo', not_matching=[‘A’, 'B', ‘C’]) # The order of A B C is not strictly required, any one of them will cause expect to fail.
> ```

Hi @gytxxsy thanks for your input! Yes, it should behave like the `pattern` param in all `expect` functions, accepts `str`, `regex`, and list of `str` or `regex`
