### ISSUE TITLE
Version 1.9.0 requires IDF plugin for projects that doesn't use IDF (RDT-767)

### ISSUE THREAD

**Issue by lucasssvaz** [espressif/pytest-embedded#278]
**Describe the bug**
The new 1.9.0 version fails to run in projects that doesn't have `pytest-embedded-idf` installed, even if the project is not related to IDF. 

You can see it in our Arduino CI: [Build Log](https://github.com/espressif/arduino-esp32/actions/runs/8825967975/job/24264680065)

**Configuration Files**
```
[pytest]
addopts = --embedded-services esp,arduino

# log related
log_cli = True
log_cli_level = INFO
log_cli_format = %(asctime)s %(levelname)s %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S

log_file = test.log
log_file_level = INFO
log_file_format = %(asctime)s %(levelname)s %(message)s
log_file_date_format = %Y-%m-%d %H:%M:%S
```

**To Reproduce**
Run a test with `--embedded-services esp,arduino` and `dut` fixture for example. It should crash.
For example:
```
def test_hello_world(dut):
    dut.expect("Hello Arduino!")

```

**Expected behavior**
Run the tests normally without the need for the IDF plugin.

**Dev Environment (please complete the following information):**
 - OS: Ubuntu
 - Python Version 3.10
 - Pytest Version 8.1.1
 - pytest-embedded Version 1.9.0

**Comment by hfudev** [comment]
@lucasssvaz Sorry for this bug. fixing it in #279

also created #280 to avoid future similar bugs.
