### ISSUE TITLE
Need an example of setting the baud rate for pytest_embedded_serial (RDT-86)

### ISSUE THREAD

**Issue by housel** [espressif/pytest-embedded#39]
Without example code that exercises it, it's not immediately obvious how to override the settings in the DEFAULT_PORT_CONFIG for pytest_embedded_serial to do things like change the baud rate or enable flow control.

**Comment by hfudev** [comment]
@housel yes, we need a way to override all the kwargs that used in third-party classes. Would add this feature later. Thanks for your idea.

**Comment by hfudev** [comment]
@housel now the pytest-embedded supports pass `baud` in parametrization. For example

```python
@pytest.mark.parametrize('baud', [
     "115200",
 ], indirect=True)
 def test_func(dut):
    pass
```
