### ISSUE TITLE
Pytest can't handle spaces in Test name (RDT-95)

### ISSUE THREAD

**Issue by tore-espressif** [espressif/pytest-embedded#59]
Consider this testcase:
``` c
TEST_CASE("chacha20 test vectors", "[libsodium]") {...}
```

Running `dut.expect_unity_test_output()` will fail because this line from the unity output will not be parsed correctly:
``` sh
C:/github_repos/idf-extra-components/libsodium/test/test_sodium.c:96:sha512 sanity check:PASS\n\n
```

causing an exception here https://github.com/espressif/pytest-embedded/blob/main/pytest-embedded/pytest_embedded/unity.py#L146

**Comment by tore-espressif** [comment]
@hfudev PTAL :)

**Comment by hfudev** [comment]
thank you @tore-espressif. fixed and added related test cases.
