### ISSUE TITLE
[idf] improve the way to pasre partition table (RDT-97)

### ISSUE THREAD

**Issue by hfudev** [espressif/pytest-embedded#62]
for now the partition table is parsed with `gen_esp32part.py`

if we use flash_args.json, we don't really need that.

**Comment by igrr** [comment]
I think having an .elf file helps to provide decoded backtraces in case of panic, so it's probably better to add .elf to the artifacts in your project.

That said, I do agree that this should be optional.

**Comment by hfudev** [comment]
@tore-espressif @igrr Thanks for your suggestions. I forgot to make this optional as well :man_facepalming: 

Created https://github.com/espressif/pytest-embedded/issues/88 to remind myself!
